feat(RHINENG-10818): Add connected status column to SystemTable
RedHatInsights/tasks-frontend pull request #214
Opened 2024-07-02 07:48 UTC by mhuth

Before:
![Screenshot from 2024-07-02 17-42-10](https://github.com/RedHatInsights/tasks-frontend/assets/4008744/c2735866-a9f7-43f2-82f9-737664d727a6)

After:
![Screenshot from 2024-07-02 17-41-53](https://github.com/RedHatInsights/tasks-frontend/assets/4008744/9add93ba-f0db-4b39-bbec-cd3bb635de16)

2024-07-02 07:51 UTC, mhuth commented
@johnsonm325 Hopefully this implementation is sufficient ... for now.

2024-07-02 07:59 UTC, InsightsDroid commented
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (4.7.3) is older than required version (6.0.0)

2024-07-03 02:05 UTC, InsightsDroid commented
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (4.7.3) is older than required version (6.0.0)

2024-07-03 02:13 UTC, InsightsDroid commented
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (4.7.3) is older than required version (6.0.0)

2024-07-03 04:41 UTC, InsightsDroid commented
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (4.7.3) is older than required version (6.0.0)

2024-07-03 06:28 UTC, PaulWay commented
Just as an addendum to this:

In order to get the `connected` status, we have to request it from Playbook Dispatcher.  This is moderately expensive, at over half a second per call, so we only do this on the page of systems we are now displaying.  We get the page of systems, we request the connection status for them and only them, we add the `connected` field value to each one, and then we pass that to be rendered into JSON.

Because it is not a database field, we can't sort it and we can't filter on it.  We don't know what the list of currently connected systems is until we ask Playbook Dispatcher for the connection status of the given list of hosts.  And it's going to slow requests down A LOT if we have to get the connection status for ALL hosts just so we can sort the connected hosts up to the top of a page of ten hosts...

2024-07-03 19:31 UTC, johnsonm325 requested changes
We'll need to wait for UX to mock-up this feature. Once we have that we can fine-tune this PR.

Thanks!

2024-07-08 02:46 UTC, InsightsDroid commented
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (4.7.3) is older than required version (6.0.0)

2024-07-08 05:44 UTC, InsightsDroid commented
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (4.7.3) is older than required version (6.0.0)

2024-07-09 07:29 UTC, InsightsDroid commented
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (4.7.3) is older than required version (6.0.0)

2024-07-09 07:56 UTC, mhuth commented
Changes to the column icons, popover, width, etc:
![Uploading Screenshot from 2024-07-09 17-22-18.png…]()

2024-07-10 04:47 UTC, InsightsDroid commented
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (4.7.3) is older than required version (6.0.0)

2024-07-11 01:11 UTC, mhuth commented
I've updated the wording slightly to more accurately represent what is this information means to a customer:
![Screenshot from 2024-07-11 11-08-24](https://github.com/RedHatInsights/tasks-frontend/assets/4008744/74616a6d-919f-4c8e-ab46-b18a3d36be7a)

2024-07-11 01:14 UTC, InsightsDroid commented
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (4.7.3) is older than required version (6.0.0)

2024-07-12 06:50 UTC, ragevou commented on src/helpers.js
> +          <DisconnectedIcon className={xsIcon} /> System not connected via RHC
```suggestion
          <DisconnectedIcon className={xsIcon} /> System is not connected via RHC
```

2024-07-12 06:52 UTC, ragevou commented on src/helpers.js
> +            Run <span className={boldText}>rhc status</span> on this system to
```suggestion
            Run <span className={boldText}>rhc status</span> to check if this system
```

2024-07-12 06:53 UTC, ragevou commented on src/helpers.js
> +            check its RHC connection to Red Hat Insights. After verifying the
```suggestion
            has RHC connection to Red Hat Insights. After verifying the
```

2024-07-12 06:53 UTC, ragevou commented on src/helpers.js
> +            connection is active, click on the{' '}
```suggestion
            connection is active, click the{' '}
```

2024-07-12 06:56 UTC, ragevou commented
hi @mhuth , I left a few suggestions to improve the microcopies. Feel free to use them. cheers! =)

2024-07-13 20:47 UTC, mhuth commented on src/helpers.js
> +          <DisconnectedIcon className={xsIcon} /> System not connected via RHC
Done!

2024-07-13 20:47 UTC, mhuth commented on src/helpers.js
> +            check its RHC connection to Red Hat Insights. After verifying the
Done!

2024-07-13 20:47 UTC, mhuth commented on src/helpers.js
> +            connection is active, click on the{' '}
Done!

2024-07-13 21:01 UTC, InsightsDroid commented
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (4.7.3) is older than required version (6.0.0)

2024-07-14 23:56 UTC, merged